# Generated by Django 5.1 on 2024-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_desc', models.TextField()),
            ],
        ),
    ]
