# Generated by Django 5.1 on 2024-08-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('instances_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instances_title', models.CharField(max_length=100)),
                ('instances_year', models.CharField(max_length=100)),
                ('instances_sem', models.CharField(max_length=100)),
            ],
        ),
    ]
